SELECT * FROM employees;
SELECT FIRST_NAMe, LAST_NAME from EMPLOYEES;
select * from JOBS;

select FIRST_NAME, SALARY from EMPLOYEES;
select FIRST_NAME, LAST_NAME, SALARY from EMPLOYEES;
Select * from DEPARTMENTS;

Select DEPARTMENT_NAME from DEPARTMENTS;
select REGION_NAME from REGIONS;